# Select image from https://hub.docker.com/r/_/php/

before_script:
# Install dependencies
- bash ci/docker_install.sh > /dev/null

image: php:5.6
cache:
  paths:
    - vendor

test:app:
  script:
  - php vendor/bin/phpunit --colors -c phpunit.xml